# Run this to download kubeconfig from remote
---
- hosts: kubernetes
  vars:
    api_port: 6443
    ddns_port: 6443
    k0sctl_conf: /etc/k0s/k0sctl_configuration.yaml

  tasks:
    - name: Get kubeconfig to /tmp/kubeconfig
      become: true
      ansible.builtin.shell: |
        # k0sctl kubeconfig -c {{ k0sctl_conf }} > /tmp/kubeconfig
        k0s kubeconfig admin > /tmp/kubeconfig

    - name: Download kubeconfig into ~/.kube folder
      ansible.builtin.fetch:
        src: /tmp/kubeconfig
        dest: ~/.kube/k0s
        # Replace the file, do not append
        flat: true

    - name: Delete kubeconfig from /tmp/kubeconfig
      become: true
      ansible.builtin.shell: |
        rm /tmp/kubeconfig

    - name: Replace API port
      ansible.builtin.shell: |
        sed -i 's/{{ api_port }}/{{ ddns_port }}/g' ~/.kube/k0s
      delegate_to: localhost
